SET ECHO ON 
DROP TABLE Players CASCADE CONSTRAINTS;
DROP TABLE Teams CASCADE CONSTRAINTS;
DROP TABLE Coaches CASCADE CONSTRAINTS;
DROP TABLE Tournaments CASCADE CONSTRAINTS;
DROP TABLE SocialMedia CASCADE CONSTRAINTS;
DROP TABLE ParticipateIn CASCADE CONSTRAINTS;
DROP TABLE PreferredChamps CASCADE CONSTRAINTS;


SET ECHO OFF
select table_name from user_tables;
select view_name from user_views;
